#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'reverse_words_order_and_swap_cases' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING sentence as parameter.
#

def reverse_words_order_and_swap_cases(sentence):
    # Write your code here
    for i in range(len(sentence)):
        if sentence[i].islower():
            sentence = sentence[:i] + sentence[i].upper() + sentence[i+1:]
        elif sentence[i].isupper():
            sentence = sentence[:i] + sentence[i].lower() + sentence[i+1:]
    Origsentence = sentence
    sentencewords = sentence.split()
    sentencewords = sentencewords[::-1]
    return ' '.join(sentencewords)

if __name__ == '__main__':
    sentence = input()
    result = reverse_words_order_and_swap_cases(sentence)
    print(result)